stages:
  - deploy
  - setup
  - run_node

deploy_to_68_job:
  stage: deploy
  script:
    - function at_68 { ssh ump@10.0.15.68 $1; }
    - at_68 "git clone git@gitlab.szdev.cn:dev/UMP-FE.git"

  environment:
    name: test
  tags:
    - test
  only:
    - master

setup_job:
  stage: setup
  script:
    - function at_68 { ssh ump@10.0.15.68 $1; }
    - at_68 "cd UMP-FE && npm config set strict-ssl false && npm config set registry 'http://registry.npm.taobao.org/' && npm install"
  tags:
    - test

run_node_68:
  stage: run_node
  script:
    - function at_68 { ssh ump@10.0.15.68 $1; }
    - at_68 "killall -q node; nohup node UMP-FE/build/server.js >/dev/null 2>&1 &"

  environment:
    name: test
  tags:
    - test
  only:
    - master
