stages:
  - deploy
  - setup
  - run_node

deploy_to_68_job:
  stage: deploy
  script:
    - function at_68 { ssh ump@10.0.15.68 $1; }
    - at_68 "git archive --format=tar --remote=git@gitlab.szdev.cn:dev/UMP-FE.git HEAD | (rm -rf ~/UMP-FE && mkdir -p ~/UMP-FE && cd ~/UMP-FE && tar xf -)"

  environment:
    name: test
  tags:
    - test
  only:
    - master

setup_job:
  stage: setup
  script:
    - function at_68 { ssh ump@10.0.15.68 $1; }
    - at_68 "cd UMP-FE && npm config set strict-ssl false && npm config set registry 'http://registry.npm.taobao.org/' && npm install"
  tags:
    - test

run_node_68:
  stage: run_node
  script:
    - function at_68 { ssh ump@10.0.15.68 $1; }
    - at_68 "sed -i -re "s/(^\s*http:\/\/localhost:8080)\s*=.*/\1='http:\/\/api\.szdev\.cn'/" src/fe/config.js"
    - at_68 "killall -q node; cd ~/UMP-FE && nohup npm run dev >/dev/null 2>&1 &"

  environment:
    name: test
  tags:
    - test
  only:
    - master
