stages:
  - deploy
  - setup
  - run_node

deploy_to_68_job:
  stage: deploy
  script:
    - git archive --format=tar --remote=git@gitlab.szdev.cn:dev/UMP-FE.git HEAD | (rm -rf /home/gitlab-runner/UMP-FE && mkdir -p /home/gitlab-runner/UMP-FE && cd /home/gitlab-runner/UMP-FE && tar xf -)

  environment:
    name: test
  tags:
    - test
  only:
    - dev

setup_job:
  stage: setup
  script:
    - cd /home/gitlab-runner/UMP-FE && npm config set strict-ssl false && npm config set registry 'https://registry.npm.taobao.org/' && npm install
  tags:
    - test

run_node_68:
  stage: run_node
  script:
    - cd /home/gitlab-runner/UMP-FE && sed -i -re "s/(^\s*axios\.defaults\.baseURL)\s*=.*/\1='http:\/\/api\.szdev\.cn'/" src/fe/config.js
    - npm run build
    - cd dist
    - pm2 startOrReload pm2.json

  environment:
    name: test
  tags:
    - test
  only:
    - dev
